//
// Created by yiwei yang on 2/5/22.
//

#ifndef RYAN_TEACHING_WINTER_SESSION_STARTPANEL_H
#define RYAN_TEACHING_WINTER_SESSION_STARTPANEL_H


class start {

};


#endif //RYAN_TEACHING_WINTER_SESSION_START_H
